default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: coursesphere_development

test:
  <<: *default
  database: coursesphere_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "coursesphere_production") %>
  url: <%= ENV["DATABASE_URL"] %>
